sudo: false
language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn install
  - yarn run build
node_js:
  - "7"
